[Service]
Environment="LD_LIBRARY_PATH=/opt/mesa-26.2.3/lib/aarch64-linux-gnu"
Environment="LIBGL_DRIVERS_PATH=/opt/mesa-26.2.3/lib/aarch64-linux-gnu/dri"
Environment="GBM_BACKENDS_PATH=/opt/mesa-26.2.3/lib/aarch64-linux-gnu/gbm"
Environment="__EGL_VENDOR_LIBRARY_FILENAMES=/opt/mesa-26.2.3/share/glvnd/egl_vendor.d/50_mesa.json"
Environment="VK_ICD_FILENAMES=/opt/mesa-26.2.3/share/vulkan/icd.d/panfrost_icd.aarch64.json"
Environment="VK_DRIVER_FILES=/opt/mesa-26.2.3/share/vulkan/icd.d/panfrost_icd.aarch64.json"
Environment="LIBGL_DRIRC_PATH=/opt/mesa-26.2.3/share/drirc.d"
