#!/bin/sh
set -e

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case "$1" in
prereqs)
	prereqs
	exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions

if prog="$(command -v fsck.ext4)"; then
	copy_exec "${prog}"
else
	echo "W: fsck.ext4 doesn't exist, can't install to initramfs" >&2
fi
